- name: Add Redis PPA
  apt_repository:
    repo: ppa:redislabs/redis
    state: present

- name: Install Redis
  apt:
    name: redis
    state: present

- name: Disable Redis service
  systemd:
    name: redis-server
    enabled: No
    state: stopped


    
- name: Allow all access to tcp port 7000
  community.general.ufw:
    rule: allow
    port: '7000'
    proto: tcp

- name: Allow all access to tcp port 7001
  community.general.ufw:
    rule: allow
    port: '7001'
    proto: tcp

- name: Allow all access to tcp port 17000
  community.general.ufw:
    rule: allow
    port: '17000'
    proto: tcp

- name: Allow all access to tcp port 17001
  community.general.ufw:
    rule: allow
    port: '17001'
    proto: tcp
    
- name: Enable ufw
  service:
    name: ufw
    state: restarted
    enabled: yes
    
- name: Configure rc.local
  template:
    src: rc.local
    dest: /etc/rc.local

- name: Add execute permission on /etc/rc.local
  file:
    path: /etc/rc.local
    mode: '+x'
    state: file

- name: Append multiple lines to /etc/sysctl.conf
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.overcommit_memory=1"
    state: present
    
- name: Create a new directory "/etc/redis/cluster"
  mkdir:
    path: /etc/redis/cluster
    mode: '0755'


- name: Create a new directory "/etc/redis/cluster/7000"
  mkdir:
    path: /etc/redis/cluster/7000
    mode: '0755'
    
- name: Create a new directory "/var/lib/redis/7000"
  mkdir:
    path: /var/lib/redis/7000
    mode: '0755'
    
- name: Create a new directory "/etc/redis/cluster/7001"
  mkdir:
    path: /etc/redis/cluster/7001
    mode: '0755'
    
- name: Create a new directory "/var/lib/redis/7001"
  mkdir:
    path: /var/lib/redis/7001
    mode: '0755'


    
# - name: Configure Redis
#   template:
#     src: redis.conf.j2
#     dest: /etc/redis/redis.conf
#   #notify: restart redis
# - name: restart redis
#   systemd:
#     name: redis-server
#     state: restarted
