- name: Add Redis PPA
  apt_repository:
    repo: ppa:redislabs/redis
    state: present

- name: Install Redis
  apt:
    name: redis
    state: present

- name: Disable Redis service
  systemd:
    name: redis-server
    enabled: No
    state: stopped


- name: Allow access to multiple TCP ports
  community.general.ufw:
    rule: allow
    proto: tcp
  loop:
    - 7000
    - 7001
    - 17000
    - 17001

    
# - name: Allow all access to tcp port 7000
#   community.general.ufw:
#     rule: allow
#     port: '7000'
#     proto: tcp

# - name: Configure Redis
#   template:
#     src: redis.conf.j2
#     dest: /etc/redis/redis.conf
#   #notify: restart redis
# - name: restart redis
#   systemd:
#     name: redis-server
#     state: restarted
