
- name: Construct Redis cluster create command
  set_fact:
    redis_cluster_command: >
      redis-cli --cluster create
      {% for host in groups['redis_master'] %}
      {{ host }}
      {% endfor %}
      {% for host in groups['redis_slave'] %}
      {{ host }}
      {% endfor %}
      --cluster-replicas 1 -a {{ redis_access_key }}

- name: Print Redis cluster command for debug
  debug:
    msg: "{{ redis_cluster_command }}"

- name: Execute Redis cluster create command
  command: "{{ redis_cluster_command }}"
  become: yes

